s3:
    rawComments: romeostestbucket
        #rawComments: romeosredditcomments
    cleanComments: clean-comments
    authors: redditnodes
    subreddits: reddit-subs
    relationships: reddit-relationships
    merged: reddit-merged

    dailyComments: redditdailycomments
    dailyEdges: redditdailyedges

reddit:
    commentsUrl: https://files.pushshift.io/reddit/comments
    commentsPath: files.pushshift.io/reddit/comments

spark:
    master: spark://10.0.0.12:7077

neo4j:
        address: bolt://127.0.0.1:7687
        username: neo4j
        password: insight

flask:
    address: none

dates:
    startDate: 2006-04
    endDate: 2017-11

tuning:
    truncation: 1
    edgePartitions: 1
    nodePartitions: 48
