s3:
    rawCommentsBucket: romeosredditcomments
    cleanCommentsBucket: redditcleancomments
    dailyCommentsBucket: redditdailycomments
    edgesBucket: redditedges5
    dailyEdgesBucket: redditdailyedges
    mergedEdgesBucket: redditmergededges
    nodesBucket: redditnodes
    mergedNodesBucket: redditmergednodes
    analysisBucket: redditanalysis
    testBucket: romeostestbucket
reddit:
    commentsUrl: https://files.pushshift.io/reddit/comments
    commentsPath: files.pushshift.io/reddit/comments
spark:
    master: spark://10.0.0.12:7077
dates:
    startDate: 2005-12
    endDate: 2005-12
tuning:
    truncation: 1
    edgePartitions: 1
    nodePartitions: 1
