s3:
    rawCommentsBucket: romeosredditcomments
    cleanCommentsBucket: clean-comments
    authorsBucket: redditnodes
    subredditsBucket: reddit-subs
    relationshipsBucket: reddit-relationships

    dailyCommentsBucket: redditdailycomments
    dailyEdgesBucket: redditdailyedges
    edgesBucket: redditedges5
    mergedEdgesBucket: redditmergededges
    nodesBucket: redditnodes
    mergedNodesBucket: redditmergednodes

    testBucket: romeostestbucket
reddit:
    commentsUrl: https://files.pushshift.io/reddit/comments
    commentsPath: files.pushshift.io/reddit/comments
spark:
    master: spark://10.0.0.12:7077
neo4j:
    address: none
flask:
    address: none
dates:
    startDate: 2006-01
    endDate: 2006-02
tuning:
    truncation: 1
    edgePartitions: 48
    nodePartitions: 48
