s3:
    rawComments: romeosredditcomments
    cleanComments: clean-comments
    authors: redditnodes
    subreddits: reddit-subs
    relationships: reddit-relationships

    dailyComments: redditdailycomments
    dailyEdges: redditdailyedges

    mergedEdges: redditmergededges
    nodes: redditnodes
    mergedNodes: redditmergednodes

    test: romeostestbucket
reddit:
    commentsUrl: https://files.pushshift.io/reddit/comments
    commentsPath: files.pushshift.io/reddit/comments
spark:
    master: spark://10.0.0.12:7077
neo4j:
    address: none
flask:
    address: none
dates:
    startDate: 2006-06
    endDate: 2016-03
tuning:
    truncation: 1
    edgePartitions: 1
    nodePartitions: 48
