s3:
    rawComments:
    cleanComments:
    authors:
    subreddits:
    relationships:
    merged: 

reddit:
    commentsUrl: https://files.pushshift.io/reddit/comments
    commentsPath: files.pushshift.io/reddit/comments

spark:
    address:

neo4j:
        address: 
        username:
        password:

flask:
    address:

dates:
    startDate:
    endDate: 

tuning:
    truncation: 1
    edgePartitions: 1
    nodePartitions: 1
