s3:
    rawCommentsBucket: romeosredditcomments
    cleanCommentsBucket: redditcleancomments
    edgesBucket: redditedges5
    mergedEdgesBucket: redditmergededges
    nodesBucket: redditnodes
    mergedNodesBucket: redditmergednodes
    analysisBucket: redditanalysis
    testBucket: romeostestbucket
reddit:
    commentsUrl: https://files.pushshift.io/reddit/comments
    commentsPath: files.pushshift.io/reddit/comments
spark:
    master: spark://10.0.0.12:7077
dates:
    startDate: 2011-04
    endDate: 2016-03
tuning:
    truncation: 5
    edgePartitions: 1
    nodePartitions: 1
