eval 'sudo apt-get update'
eval 'sudo apt install python3-pip'
eval 'sudo apt install default-jre'
eval 'sudo apt install default-jdk'
eval 'sudo apt install awscli'
#eval 'pip3 install pyspark'
eval 'pip3 install datetime'
eval 'pip3 install monthdelta'
eval 'pip3 install pyyaml'
eval 'pip3 install awscli'
#eval 'pip3 install neo4j'
#eval 'pip3 install flask'
